// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABaN087lk9DotKGJJ_fA7yTw6ZmGaOPRU',
    appId: '1:1036463058656:web:a88b14290c65f5840d6a85',
    messagingSenderId: '1036463058656',
    projectId: 'eklinikk-18d73',
    authDomain: 'eklinikk-18d73.firebaseapp.com',
    storageBucket: 'eklinikk-18d73.appspot.com',
    measurementId: 'G-KJW94MSMV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVKS6lmTG7T58eLyvmDKZZfMsxdMnZchw',
    appId: '1:1036463058656:android:bf180d3dddefbd1c0d6a85',
    messagingSenderId: '1036463058656',
    projectId: 'eklinikk-18d73',
    storageBucket: 'eklinikk-18d73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTboNxzrt_7iIeZL6EO8YS6HkxdWEUVeo',
    appId: '1:1036463058656:ios:161337170bd3c4220d6a85',
    messagingSenderId: '1036463058656',
    projectId: 'eklinikk-18d73',
    storageBucket: 'eklinikk-18d73.appspot.com',
    iosBundleId: 'com.example.eKlinikDrHMChalim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTboNxzrt_7iIeZL6EO8YS6HkxdWEUVeo',
    appId: '1:1036463058656:ios:9cbf21bee2863d470d6a85',
    messagingSenderId: '1036463058656',
    projectId: 'eklinikk-18d73',
    storageBucket: 'eklinikk-18d73.appspot.com',
    iosBundleId: 'com.example.eKlinikDrHMChalim.RunnerTests',
  );
}
